=== matijapetrovic/xml-projekat/data/xsd/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns="http://www.ftn.uns.ac.rs/xml/tim11/resenje"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
	elementFormDefault="qualified"
	targetNamespace="http://www.ftn.uns.ac.rs/xml/tim11/resenje"
	xmlns:re="http://www.ftn.uns.ac.rs/xml/tim11/resenje"
	vc:minVersion="1.1">
	<xs:element name="Resenje">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BrojResenja">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="\d{3}-\d{2}-\d{4}/\d{4}-\d{2}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="DatumResenja" type="xs:date"/>
				<xs:element name="Uvod" type="re:CTUvod"/>
				<xs:element name="Sadrzaj" type="re:CTResenje"/>
				<xs:element name="Obrazlozenje" type="re:CTObrazlozenje"/>
				<xs:element name="Poverenik" type="re:CTPoverenik"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="CTUvod" mixed="true">
		<xs:sequence>
			<xs:element name="DatumZalbe" type="xs:date"/>
			<xs:element name="OrganVlasti" type="xs:string"/>
			<xs:element  minOccurs = "0" maxOccurs="unbounded" name="PozivNaZakon" type="re:CTPozivNaZakon"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTPozivNaZakon">
		<xs:sequence>
			<xs:element name="Zakon" type="re:CTZakon"></xs:element>
			<xs:element name="BrojeviSluzbenogGlasnika">
			  <xs:complexType>
				  <xs:sequence>
					  <xs:element maxOccurs="unbounded" name="Broj">
						  <xs:simpleType>
							  <xs:restriction base="xs:string">
								  <xs:pattern value="[1-9][0-9]*/[0-9]{2}"></xs:pattern>
							  </xs:restriction>
						  </xs:simpleType>
					  </xs:element>
				  </xs:sequence>
			  </xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTZakon">
		<xs:sequence>
			<xs:element minOccurs = "1" maxOccurs="unbounded" name="Clan" type="xs:positiveInteger"/>
			<xs:element minOccurs = "0" maxOccurs="1" name="Stav" type="xs:positiveInteger"/>
			<xs:element minOccurs = "0" maxOccurs="1" name="Tacka" type="xs:positiveInteger"/>
			<xs:element name="NazivZakona">
		        <xs:complexType>
		          <xs:simpleContent>
		            <xs:extension base="xs:string">
		              <xs:attribute name="type" use="required"/>
		              <xs:attribute name="property" use="required"/>
		            </xs:extension>
		          </xs:simpleContent>
		        </xs:complexType>
      </xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTResenje">
		<xs:sequence>
			<xs:element name="OrganVlasti">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="type" use="required"/>
              <xs:attribute name="property" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
			<xs:element ref="re:CTUstanova"></xs:element>
			<xs:element name="Ishod" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
   
	<xs:complexType name="CTObrazlozenje">
		<xs:sequence>
			<xs:element name="PredmetZalbe" type="re:CTPredmetZalbe"></xs:element>
			<xs:element name="Postupak" type="re:CTPostupak"></xs:element>
			<xs:element name="Odluka" type="re:CTOdluka"></xs:element>
		</xs:sequence>
		<xs:attribute name="about" use="required" type="xs:anyURI"/>
		<xs:attribute name="vocab" use="required" type="xs:anyURI"/>
	</xs:complexType>
	
	<xs:complexType name="CTPredmetZalbe">
		<xs:sequence>
			<xs:element name="DatumIzjave" type="xs:date"></xs:element>
			<xs:element name="OrganVlasti" type="xs:string"></xs:element>
			<xs:element name="DatumPotrazivanjaInformacija">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:date">
              <xs:attribute name="type" use="required"/>
              <xs:attribute name="property" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTPostupak">
		<xs:sequence>
			<xs:element name="DatumPostupka" type="xs:date"></xs:element>
			<xs:element ref="re:CTUstanova"></xs:element>
			<xs:element name="Zakon" type="re:CTZakon"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTOdluka">
		<xs:sequence>
			<xs:element name="Zakon" type="re:CTZakon"></xs:element>
			<xs:element name="Lice" type="xs:string"></xs:element>
			<xs:element name="Mesto">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="type" use="required"/>
              <xs:attribute name="property" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
			<xs:element name="Iznos" type="xs:positiveInteger"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTPoverenik">
		<xs:sequence>
			<xs:element name="Ime">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="type" use="required"/>
              <xs:attribute name="property" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
			<xs:element name="Prezime">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="type" use="required"/>
              <xs:attribute name="property" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="CTUstanova">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Naziv">
			      <xs:complexType>
			        <xs:simpleContent>
			          <xs:extension base="xs:string">
			            <xs:attribute name="type" use="required"/>
			            <xs:attribute name="property" use="required"/>
			          </xs:extension>
			        </xs:simpleContent>
			      </xs:complexType>
       		 </xs:element>
				<xs:element name="Adresa" type="xs:string"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== matijapetrovic/xml-projekat/data/xml/resenje1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Resenje xmlns="http://www.ftn.uns.ac.rs/xml/tim11/resenje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml/tim11/resenje file:/C:/Dev/Faks/xml/xml-projekat/data/xsd/resenje.xsd">
    <BrojResenja>000-00-0000/0000-00</BrojResenja>
    <Svrha>ZalbaOsnovanaNalazeSe</Svrha>
    <DatumResenja>2006-05-04</DatumResenja>
    <Uvod>
        Poverenik za informacije od javnog značaja i zaštitu podataka o ličnosti, u postupku po albi
        koju je izjavio AA, zbog nepostupanja
        <OrganVlasti>OrganVlasti0</OrganVlasti> po njegovom zahtevu od
        <DatumZalbe>2006-05-04</DatumZalbe>
        godine za pristup informacijama od javnog značaja, na osnovu člana 35. stav 1. tačka 5. Zakona o slobodnom pristupu
        informacijama od javnog značaja („Sl. glasnik RS“, br. 120/04, 54/07, 104/09 i 36/10), a u vezi sa
        članom 4. tačka 22. Zakona o zaštiti podataka o ličnosti („Sl. glasnik RS“, broj 87/18), kao i člana
        23. i člana 24. stav 4. Zakona o slobodnom pristupu informacijama od javnog značaja i člana 173.
        stav 2. Zakona o opštem upravnom postupku („Sl. glasnik RS“, br. 18/2016 i 95/2018-autentično
        tumačenje), donosi
    </Uvod>
    <Sadrzaj>
        I Nalaze se<Ustanova>
            <Naziv type="type3" property="property3">Uciteljskom fakultetu</Naziv>
            <Adresa>u Prizrenu</Adresa>
        </Ustanova>
         sa privremenim sedištem u Leposaviću, da
        bez odlaganja, a najkasnije u roku od pet dana od dana prijema ovog rešenja, obavesti AA, da li
        poseduje tražene informacije odnosno dokument u kome su iste sadržane, i to: Ugovor o radu koji
        je kao poslednji potpisan između tog Fakulteta i BB, te da mu, ukoliko takav dokument poseduje
        dostavi kopiju istog elektronskom poštom na adresu … ili poštom, s tim što će pre dostavljanja
        zaštititi i učiniti nedostupnim podatke o ličnosti kojima bi se povredilo pravo na privatnost
        lica na koje se informacije odnose, kao što su: adresa stanovanja, lični matični broj građana, ime
        oca, radni staž, prosečna ocena studiranja i sl. ukoliko su takvi podaci sadržani u traženom
        dokumentu.
        <Ishod>II O izvršenju rešenja Učiteljski fakultet u Prizrenu sa privremenim sedištem u
        Leposaviću, će obavestiti Poverenika u roku od sedam dana od prijema ovog rešenja.</Ishod>
    </Sadrzaj>
    <Obrazlozenje about="http://www.oxygenxml.com/" vocab="http://www.oxygenxml.com/">
        <PredmetZalbe>
            AA , kao trazilac informacija izjavio je dana
            <DatumIzjave>2020-07-05</DatumIzjave> godine zalbu POvereniku zbog nepostupanja
            <OrganVlasti>Uciteljskog fakulteta u prizrenu </OrganVlasti>
            po njegovom zahtevu od
            <DatumPotrazivanjaInformacija type="type5" property="property5">2020-04-16</DatumPotrazivanjaInformacija>
            godine za pristup informacijama od javnog znacaja i u prilogu
            dostavion kopiju istog.
        </PredmetZalbe>
        <Postupak>
            Postupajuci po zalbi, Poverenik je dana
            <DatumPostupka>2006-05-04</DatumPostupka> godine uputio je istu na izjasnjenje
            <Ustanova>
                <Naziv type="type7" property="property7">Uciteljskom fakultetu u </Naziv>
                <Adresa>Prizrenu sa privremenim sedistem u Leposavicu</Adresa>
            </Ustanova>
            kao organu vlasti u
            smislu člana 3. Zakona o slobodnom pristupu informacijama od javnog značaja i zatražio da se
            izjasni o navodima žalbe, posebno o razlozima nepostupanja u zakonskom roku po podnetom zahtevu
            u skladu sa odredbama člana 16. st.1-9. ili st. 10. Zakona, ostavljajući rok od osam dana, povodom
            čega nije dobio odgovor.
        </Postupak>
        <Odluka>
            Po razmatranju žalbe i ostalih spisa ovog predmeta, doneta je odluka kao u dispozitivu
            rešenja iz sledećih razloga:
            Uvidom u spise predmeta utvrđeno je da je AA, dana 16.04.2020. godine, podneo Učiteljskom
            fakultetu u Prizrenu sa privremenim sedištem u Leposaviću, zahtev za pristup informacijama
            od javnog značaja, elektronskom poštom, kojim je tražio informacije od javnog značaja, bliže
            navedene u stavu I dispozitiva ovog rešenja.
            Takođe je uvidom u spise predmeta utvrđeno da po zahtevu žalioca od 16.04.2020. godine,
            organ vlasti nije postupio, što je bio dužan da učini bez odlaganja, a najkasnije u roku od 15 dana
            od prijema zahteva te da žalioca, u smislu člana 16. stav 1. Zakona o slobodnom pristupu

            <Lice>Lice0</Lice>
            <Mesto type="type13" property="property13">Mesto0</Mesto>
            <Iznos>50</Iznos>
        </Odluka>
    </Obrazlozenje>
    <Poverenik>
        <Ime type="type15" property="property15">Ime0</Ime>
        <Prezime type="type17" property="property17">Prezime0</Prezime>
    </Poverenik>
</Resenje>
