=== matijapetrovic/xml-projekat/data/xsd/zahtevcir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:rdfa="http://www.w3.org/ns/rdfa#"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	targetNamespace="http://www.ftn.uns.ac.rs/xml/tim11/zahtev"
	xmlns:za="http://www.ftn.uns.ac.rs/xml/tim11/zahtev">
	
	<xs:element name="Zahtev">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Organ" type="za:CTOrgan"/>
				<xs:element name="Zahtevi" type="za:CTZahtevi"/>
				<xs:element name="OstaliPodaci" type="za:CTOstaliPodaci"/>
				<xs:element name="TrazilacInformacija" type="za:CTTrazilacInformacija"/>
			</xs:sequence>
			<xs:attribute name="vocab" fixed="http://www.ftn.uns.ac.rs/xml/tim11/predicate" use="required"/>
			<xs:attribute name="about" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="CTOrgan">
		<xs:sequence>
			<xs:element name="Naziv">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute fixed="izdatoOdStrane" form="unqualified" name="property" use="required"/>
							<xs:attribute fixed="xs:string" name="datatype" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Sediste" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTParagraf1">
		<xs:sequence>
			<xs:element name="Clan" fixed="15" type="xs:positiveInteger"></xs:element>
			<xs:element name="Stav" fixed="1" type="xs:positiveInteger"></xs:element>
			<xs:element name="Zakon" fixed="Zakon o slobodnom pristupu informacijama od javnog značaja" type="xs:string"></xs:element>
			<xs:element name="SluzbeniGlasnik">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Naziv" fixed="Sluzbeni glasnik Republike Srbije" type="xs:string"/>
						<xs:element name="Brojevi">
							<xs:complexType>
								<xs:sequence>
									<xs:element maxOccurs="unbounded" name="broj">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="[1-9][0-9]*\/[0-9]{2}"></xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTZahtevi">
		<xs:sequence>
		  <xs:element minOccurs="0" name="Obavestenje"/>
		  <xs:element minOccurs="0" name="Uvid"/>
		  <xs:element minOccurs="0" name="Kopija"/>
		  <xs:element minOccurs="0" name="DostavljanjeKopije">
		  	<xs:complexType>
		  		<xs:sequence>
		  			<xs:element name="NacinDostave" type="za:CTNacinDostave"/>
		  		</xs:sequence>
		  	</xs:complexType>
		  </xs:element>
		  <xs:element name="Informacije" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTNacinDostave">
		<xs:choice>
		  <xs:element name="Posta" />
		  <xs:element name="ElektronskaPosta"/>
		  <xs:element name="Faks"/>
		  <xs:element name="Drugo">
			  <xs:complexType>
			  	<xs:sequence>
			  		<xs:element name="Opis">
			  			<xs:simpleType>
			  				<xs:restriction base="xs:string">
			  					<xs:minLength value="1"/>
			  				</xs:restriction>
			  			</xs:simpleType>
			  		</xs:element>
			  	</xs:sequence>
			  </xs:complexType>
		  </xs:element>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="CTOstaliPodaci">
		<xs:sequence>
			<xs:element name="Mesto">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute fixed="podnesenU" form="unqualified" name="property" use="required"/>
							<xs:attribute fixed="xs:string" name="datatype" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Datum">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:date">
							<xs:attribute fixed="podnesenDatuma" form="unqualified" name="property" use="required"/>
							<xs:attribute fixed="xs:date" name="datatype" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CTTrazilacInformacija">
		<xs:sequence>
			<xs:element name="Ime">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute fixed="imeTrazioca" form="unqualified" name="property" use="required"/>
							<xs:attribute fixed="xs:string" name="datatype" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Prezime">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute fixed="prezimeTrazioca" form="unqualified" name="property" use="required"/>
							<xs:attribute fixed="xs:string" name="datatype" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Adresa" type="xs:string"/>
			<xs:element name="Kontakt" type="xs:string"/>
		</xs:sequence>
		
		<xs:attribute name="vocab" fixed="http://www.ftn.uns.ac.rs/xml/tim11/predicate" use="required"/>
		<xs:attribute name="about" use="required" />
		<xs:attribute name="rel" fixed="podneoZahtev" use="required"/>
		<xs:attribute name="href" use="required" />
	</xs:complexType>
</xs:schema>

=== matijapetrovic/xml-projekat/data/xml/zahtev1.xml
<?xml version="1.0" encoding="UTF-8"?>
<za:Zahtev xmlns="http://www.w3.org/ns/rdfa#"
 xmlns:za="http://www.ftn.uns.ac.rs/xml/tim11/zahtev"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml/tim11/zahtev file:/C:/Dev/Faks/xml/xml-projekat/data/xsd/zahtevcir.xsd" vocab="http://www.ftn.uns.ac.rs/xml/tim11/predicate" about="http://www.ftn.uns.ac.rs/xml/tim11/zahtev/1234">
    <za:Organ>
        <za:Naziv property="izdatoOdStrane" datatype="xs:string">Naziv0</za:Naziv>
        <za:Sediste>Sediste0</za:Sediste>
    </za:Organ>
    <za:Zahtevi>
        <za:Informacije>Informacije0</za:Informacije>
    </za:Zahtevi>
    <za:OstaliPodaci>
        <za:Mesto property="podnesenU" datatype="xs:string">Mesto0</za:Mesto>
        <za:Datum property="podnesenDatuma" datatype="xs:date">2006-05-04</za:Datum>
    </za:OstaliPodaci>
    <za:TrazilacInformacija vocab="http://www.ftn.uns.ac.rs/xml/tim11/predicate" about="http://www.ftn.uns.ac.rs/xml/tim11/gradjanin/1234" rel="podneoZahtev" href="http://www.ftn.uns.ac.rs/xml/tim11/zahtev/1234">
        <za:Ime property="imeTrazioca" datatype="xs:string">Ime0</za:Ime>
        <za:Prezime property="prezimeTrazioca" datatype="xs:string">Prezime0</za:Prezime>
        <za:Adresa>Adresa0</za:Adresa>
        <za:Kontakt>Kontakt0</za:Kontakt>
    </za:TrazilacInformacija>
</za:Zahtev>
