=== matijapetrovic/xml-projekat/data/xsd/zalbanaodlukucir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.ftn.uns.ac.rs/xml/tim11/zalbanaodluku"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
    elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/xml/tim11/zalbanaodluku"
    xmlns:zod="http://www.ftn.uns.ac.rs/xml/tim11/zalbanaodluku"
    vc:minVersion="1.1">

    <xs:element name="ZalbaNaOdluku">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="primalac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="adresaPrimaoca" type="zod:ZAdresa"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sadrzaj">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="paragraf1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="predmetSlanja">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="property" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="osoba" type="zod:ZOsoba"/>
                                        <xs:element name="naziv">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="2"/>
                                                  <xs:maxLength value="100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="adresa" type="zod:ZAdresa"/>
                                        <xs:element minOccurs="1" name="sediste">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                  <xs:maxInclusive value="50"/>
                                                  <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="paragraf2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nazivOrgana">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="property" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="broj">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                  <xs:maxInclusive value="300"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="godina">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                  <xs:minInclusive value="2000"/>
                                                  <xs:maxInclusive value="2100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="paragraf3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dan">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                  <xs:maxInclusive value="31"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="godina">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                  <xs:minExclusive value="2000"/>
                                                  <xs:maxExclusive value="2100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="razlog">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  <xs:maxLength value="500"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="paragraf4">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="zakljucak">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="razlog">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  <xs:maxLength value="500"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="zakonPodnosenjaZalbe">
                                                      <xs:complexType>
                                                          <xs:simpleContent>
                                                              <xs:extension base="xs:string">
                                                                  <xs:attribute name="property" use="required"/>
                                                              </xs:extension>
                                                          </xs:simpleContent>
                                                      </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podnosilacZalbe">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="osoba" type="zod:ZOsoba"/>
                            <xs:element name="adresa" type="zod:ZAdresa"/>
                            <xs:element maxOccurs="1" minOccurs="0" name="drugiPodaci">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="0"/>
                                        <xs:maxLength value="500"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="potpis">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podaciPodnosenjaZalbe">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mesto">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="200"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dan">
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:maxInclusive value="31"/>
                                        <xs:minInclusive value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="godina">
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:maxInclusive value="2100"/>
                                        <xs:minInclusive value="2000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="napomena">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lista">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="stavka1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  <xs:maxLength value="500"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="stavka2">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  <xs:maxLength value="500"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType mixed="false" name="ZAdresa">
        <xs:sequence>
            <xs:element name="mesto">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                        <xs:maxLength value="200"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="200"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ZOsoba">
        <xs:sequence>
            <xs:element name="ime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="prezime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== matijapetrovic/xml-projekat/data/xml/zalbanaodluku1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ZalbaNaOdluku xmlns="http://www.ftn.uns.ac.rs/xml/tim11/zalbanaodluku"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml/tim11/zalbanaodluku file:/C:/Dev/Faks/xml/xml-projekat/data/xsd/zalbanaodlukucir.xsd">
    <primalac>
        <adresaPrimaoca>
            <mesto property="property1">mesto0</mesto>
            <ulica>ulica0</ulica>
            <broj>100</broj>
        </adresaPrimaoca>
    </primalac>
    <sadrzaj>
        <paragraf1>
            <predmetSlanja property="property3">predmetSlanja0</predmetSlanja>
            <osoba>
                <ime property="property5">ime0</ime>
                <prezime property="property7">prezime0</prezime>
            </osoba>
            <naziv>naziv0</naziv>
            <adresa>
                <mesto property="property9">mesto1</mesto>
                <ulica>ulica1</ulica>
                <broj>100</broj>
            </adresa>
            <sediste>26</sediste>
        </paragraf1>
        <paragraf2>
            <nazivOrgana property="property11">nazivOrgana0</nazivOrgana>
            <broj>150</broj>
            <godina>2050</godina>
        </paragraf2>
        <paragraf3>
            <dan>16</dan>
            <godina>2050</godina>
            <razlog>razlog0</razlog>
        </paragraf3>
        <paragraf4>
            <zakljucak>
                <razlog>razlog1</razlog>
                <zakonPodnosenjaZalbe property="property13">zakonPodnosenjaZalbe0</zakonPodnosenjaZalbe>
            </zakljucak>
        </paragraf4>
    </sadrzaj>
    <podnosilacZalbe>
        <osoba>
            <ime property="property15">ime1</ime>
            <prezime property="property17">prezime1</prezime>
        </osoba>
        <adresa>
            <mesto property="property19">mesto2</mesto>
            <ulica>ulica2</ulica>
            <broj>100</broj>
        </adresa>
        <potpis>potpis0</potpis>
    </podnosilacZalbe>
    <podaciPodnosenjaZalbe>
        <mesto>mesto3</mesto>
        <dan>16</dan>
        <godina>2050</godina>
    </podaciPodnosenjaZalbe>
    <napomena>
        <lista>
            <stavka1>stavka10</stavka1>
            <stavka2>stavka20</stavka2>
        </lista>
    </napomena>
</ZalbaNaOdluku>
