=== matijapetrovic/xml-projekat/documents/schemas/obavestenjecir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns="http://www.ftn.uns.ac.rs/xml/tim11/obavestenje"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
    elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/xml/tim11/obavestenje"
    xmlns:ob="http://www.ftn.uns.ac.rs/xml/tim11/obavestenje"
    vc:minVersion="1.1">

	<xs:element name="Obavestenje">
	    <xs:complexType>
	        <xs:sequence>
	            <xs:element name="BrojPredmeta" type="xs:string"/>
	            <xs:element name="Datum" type="xs:date"/>
	            <xs:element name="Organ" type="ob:CTOrgan"/>
	            <xs:element name="PodnosiocZahteva" type="ob:CTPodnosiocZahteva"/>
	            <xs:element name="TrazenaInformacija" type="ob:CTTrazenaInformacija"/>
	            <xs:element name="InformacijeOUvidu" type="ob:CTInformacijeOUvidu"/>
	            <xs:element name="Troskovi" type="ob:CTTroskovi"/>
	            <xs:element name="InformacijeOUplati" type="ob:CTInformacijeOUplati"/>
	            <xs:element name="Dostavljeno">
	                <xs:simpleType>
	                    <xs:restriction base="xs:string">
	                        <xs:enumeration value="Imenovanom"/>
	                        <xs:enumeration value="Arhivi"/>
	                    </xs:restriction>
	                </xs:simpleType>
	            </xs:element>
	        </xs:sequence>
	    </xs:complexType>
	</xs:element>
    <xs:complexType name="CTOrgan">
        <xs:sequence>
            <xs:element name="Naziv" type="xs:string"/>
            <xs:element name="Sediste" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTPodnosiocZahteva">
        <xs:sequence>
            <xs:element name="Ime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Prezime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Naziv" type="xs:string"/>
            <xs:element name="Adresa" type="ob:CTAdresa"/>
        </xs:sequence>
    </xs:complexType>
	<xs:complexType name="CTInformacijeOUvidu">
	    <xs:sequence>
	        <xs:element name="Datum">
	            <xs:complexType>
	                <xs:simpleContent>
	                    <xs:extension base="xs:date">
	                        <xs:attribute name="property" use="required"/>
	                    </xs:extension>
	                </xs:simpleContent>
	            </xs:complexType>
	        </xs:element>
	        <xs:element name="Satnica" type="xs:time"/>
	        <xs:element name="SatnicaOd" type="xs:time"/>
	        <xs:element name="SatnicaDo" type="xs:time"/>
	        <xs:element name="Adresa" type="ob:CTAdresa"/>
	        <xs:element name="BrojKancelarije" type="xs:positiveInteger"/>
	    </xs:sequence>
	</xs:complexType>
    <xs:complexType name="CTAdresa">
        <xs:sequence>
            <xs:element name="Mesto">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTTrazenaInformacija">
        <xs:sequence>
            <xs:element name="DatumZahteva">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:date">
                            <xs:attribute name="property" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="OpisInformacije" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTTroskovi">
        <xs:sequence>
            <xs:element fixed="3.0" name="CenaA4" type="xs:decimal"/>
            <xs:element fixed="6.0" name="CenaA3" type="xs:decimal"/>
            <xs:element fixed="35.0" name="CenaCD" type="xs:decimal"/>
            <xs:element fixed="20.0" name="CenaDisketa" type="xs:decimal"/>
            <xs:element fixed="40.0" name="CenaDVD" type="xs:decimal"/>
            <xs:element fixed="150.0" name="CenaAudioKaseta" type="xs:decimal"/>
            <xs:element fixed="300.0" name="CenaVideoKaseta" type="xs:decimal"/>
            <xs:element fixed="30.0" name="CenaEDokument" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTInformacijeOUplati">
        <xs:sequence>
            <xs:element name="UkupniTroskovi" type="xs:decimal"/>
            <xs:element fixed="840-0000742328843-30" name="ZiroRacun">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element fixed="97" name="BrojModela">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== matijapetrovic/xml-projekat/data/xml/obavestenje1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ob:Obavestenje xmlns="http://www.w3.org/ns/rdfa#"
 xmlns:ob="http://www.ftn.uns.ac.rs/xml/tim11/obavestenje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml/tim11/obavestenje file:/C:/Dev/Faks/xml/xml-projekat/data/xsd/obavestenjecir.xsd" vocab="http://www.ftn.uns.ac.rs/xml/tim11/predicate" about="http://www.ftn.uns.ac.rs/xml/tim11/obavestenje/1234">
    <ob:BrojPredmeta property="brojPredmeta" datatype="xs:string">BrojPredmeta0</ob:BrojPredmeta>
    <ob:Datum property="podnesenoDatuma" datatype="xs:date">2006-05-04</ob:Datum>
    <ob:Organ>
        <ob:Naziv property="izdatoOdStrane" datatype="xs:string">Naziv0</ob:Naziv>
        <ob:Sediste>Sediste0</ob:Sediste>
    </ob:Organ>
    <ob:PodnosiocZahteva>
        <ob:Ime property="imePodnosoica" datatype="xs:string">Ime0</ob:Ime>
        <ob:Prezime property="prezimePodnosioca" datatype="xs:string">Prezime0</ob:Prezime>
        <ob:Naziv>Naziv1</ob:Naziv>
        <ob:Adresa>
            <ob:Mesto>Mesto0</ob:Mesto>
            <ob:Ulica>Ulica0</ob:Ulica>
            <ob:Broj>50</ob:Broj>
        </ob:Adresa>
    </ob:PodnosiocZahteva>
    <ob:TrazenaInformacija>
        <ob:DatumZahteva>2006-05-04</ob:DatumZahteva>
        <ob:OpisInformacije>OpisInformacije0</ob:OpisInformacije>
    </ob:TrazenaInformacija>
    <ob:InformacijeOUvidu>
        <ob:Datum>2006-05-04</ob:Datum>
        <ob:Satnica>01:01:01.001</ob:Satnica>
        <ob:SatnicaOd>01:01:01.001</ob:SatnicaOd>
        <ob:SatnicaDo>01:01:01.001</ob:SatnicaDo>
        <ob:Adresa>
            <ob:Mesto>Mesto1</ob:Mesto>
            <ob:Ulica>Ulica1</ob:Ulica>
            <ob:Broj>50</ob:Broj>
        </ob:Adresa>
        <ob:BrojKancelarije>50</ob:BrojKancelarije>
    </ob:InformacijeOUvidu>
    <ob:Troskovi>
        <ob:CenaA4>3.0</ob:CenaA4>
        <ob:CenaA3>6.0</ob:CenaA3>
        <ob:CenaCD>35.0</ob:CenaCD>
        <ob:CenaDisketa>20.0</ob:CenaDisketa>
        <ob:CenaDVD>40.0</ob:CenaDVD>
        <ob:CenaAudioKaseta>150.0</ob:CenaAudioKaseta>
        <ob:CenaVideoKaseta>300.0</ob:CenaVideoKaseta>
        <ob:CenaEDokument>30.0</ob:CenaEDokument>
    </ob:Troskovi>
    <ob:InformacijeOUplati>
        <ob:UkupniTroskovi>0</ob:UkupniTroskovi>
        <ob:ZiroRacun>840-0000742328843-30</ob:ZiroRacun>
        <ob:BrojModela>97</ob:BrojModela>
    </ob:InformacijeOUplati>
    <ob:Dostavljeno>Imenovanom</ob:Dostavljeno>
</ob:Obavestenje>

=== matijapetrovic/xml-projekat/documents/instances/obavestenjecir.xml
<?xml version="1.0" encoding="UTF-8"?>
<ob:Obavestenje xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:ob="obavestenje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="obavestenje file:/C:/Users/matth/Documents/OxygenXMLEditor/projects/obavestenjecir.xsd">
    <ob:BrojPredmeta>BrojPredmeta0</ob:BrojPredmeta>
    <ob:Datum>2006-05-04</ob:Datum>
    <ob:Organ>
        <ob:Naziv>Naziv0</ob:Naziv>
        <ob:Sediste>Sediste0</ob:Sediste>
    </ob:Organ>
    <ob:PodnosiocZahteva>
        <ob:Ime>Ime0</ob:Ime>
        <ob:Prezime>Prezime0</ob:Prezime>
        <ob:Naziv>Naziv1</ob:Naziv>
        <ob:Adresa>
            <ob:Mesto>Mesto0</ob:Mesto>
            <ob:Ulica>Ulica0</ob:Ulica>
            <ob:Broj>50</ob:Broj>
        </ob:Adresa>
    </ob:PodnosiocZahteva>
    <ob:TrazenaInformacija>
        <ob:DatumZahteva>2006-05-04</ob:DatumZahteva>
        <ob:OpisInformacije>OpisInformacije0</ob:OpisInformacije>
    </ob:TrazenaInformacija>
    <ob:InformacijeOUvidu>
        <ob:Datum>2006-05-04</ob:Datum>
        <ob:Satnica>01:01:01.001</ob:Satnica>
        <ob:SatnicaOd>01:01:01.001</ob:SatnicaOd>
        <ob:SatnicaDo>01:01:01.001</ob:SatnicaDo>
        <ob:Adresa>
            <ob:Mesto>Mesto1</ob:Mesto>
            <ob:Ulica>Ulica1</ob:Ulica>
            <ob:Broj>50</ob:Broj>
        </ob:Adresa>
        <ob:BrojKancelarije>50</ob:BrojKancelarije>
    </ob:InformacijeOUvidu>
    <ob:Troskovi>
        <ob:CenaA4>3.0</ob:CenaA4>
        <ob:CenaA3>6.0</ob:CenaA3>
        <ob:CenaCD>35.0</ob:CenaCD>
        <ob:CenaDisketa>20.0</ob:CenaDisketa>
        <ob:CenaDVD>40.0</ob:CenaDVD>
        <ob:CenaAudioKaseta>150.0</ob:CenaAudioKaseta>
        <ob:CenaVideoKaseta>300.0</ob:CenaVideoKaseta>
        <ob:CenaEDokument>30.0</ob:CenaEDokument>
    </ob:Troskovi>
    <ob:InformacijeOUplati>
        <ob:UkupniTroskovi>0</ob:UkupniTroskovi>
        <ob:ZiroRacun>840-0000742328843-30</ob:ZiroRacun>
        <ob:BrojModela>97</ob:BrojModela>
    </ob:InformacijeOUplati>
    <ob:Dostavljeno>Imenovanom</ob:Dostavljeno>
</ob:Obavestenje>
