=== matijapetrovic/xml-projekat/documents/schemas/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    targetNamespace="resenje" xmlns:re="resenje"
    vc:minVersion="1.1">
    <xs:element name="resenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="BrojResenja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d{3}-\d{2}-\d{4}/\d{4}-\d{2}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="DatumResenja" type="xs:date"/>
                <xs:element name="Uvod" type="re:CTUvod"/>
                <xs:element name="Sadrzaj" type="re:CTSadrzaj"/>
                <xs:element name="Obrazlozenje" type="re:CTObrazlozenje"/>
                <xs:element name="Poverenik" type="re:CTPoverenik"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="CTUvod" mixed="true">
        <xs:sequence>
            <xs:element name="DatumZalbe" type="xs:date"/>
            <xs:element name="OrganVlasti" type="xs:string"/>
            <xs:element  minOccurs = "0" maxOccurs="unbounded" name="PozivNaZakon" type="re:CTPozivNaZakon"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="CTPozivNaZakon">
        <xs:sequence>
            <xs:element minOccurs = "1" maxOccurs="unbounded" name="Clan" type="xs:positiveInteger"/>
            <xs:element minOccurs = "0" maxOccurs="1" name="Stav" type="xs:positiveInteger"/>
            <xs:element minOccurs = "0" maxOccurs="1" name="Tacka" type="xs:positiveInteger"/>
            <xs:element name="NazivZakona" type="xs:string"/>
            <xs:element name="BrojeviSluzbenogGlasnika">
              <xs:complexType>
                  <xs:sequence>
                      <xs:element maxOccurs="unbounded" name="Broj">
                          <xs:simpleType>
                              <xs:restriction base="xs:string">
                                  <xs:pattern value="[1-9][0-9]*/[0-9]{2}"></xs:pattern>
                              </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                  </xs:sequence>
              </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="CTSadrzaj">
        <xs:sequence>
            <xs:element name="OrganVlasti" type="xs:string"/>
            <xs:element name="Ishod" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:complexType name="CTObrazlozenje">
        <xs:sequence>
            <xs:element name="Paragraf1" type="re:CTParagraf1"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="CTParagraf1">
        <xs:sequence>
            <xs:element name="DatumIzjave" type="xs:date"></xs:element>
            <xs:element name="OrganVlasti" type="xs:string"></xs:element>
            <xs:element name="DatumPotrazivanjaInformacija" type="xs:date"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="CTPoverenik">
        <xs:sequence>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== matijapetrovic/xml-projekat/documents/schemas/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<re:resenje xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:re="resenje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="resenje file:/C:/FAKS/7%20semestar/XML%20veb%20serivisi/xml-projekat/documents/schemas/resenje.xsd">
    <re:BrojResenja>000-00-0000/0000-00</re:BrojResenja>
    <re:DatumResenja>2006-05-04</re:DatumResenja>
    <re:Uvod>
        <re:DatumZalbe>2006-05-04</re:DatumZalbe>
        <re:OrganVlasti>OrganVlasti0</re:OrganVlasti>
    </re:Uvod>
    <re:Sadrzaj>
        <re:OrganVlasti>OrganVlasti1</re:OrganVlasti>
        <re:Ishod>Ishod0</re:Ishod>
    </re:Sadrzaj>
    <re:Obrazlozenje>
        <re:Paragraf1>
            <re:DatumIzjave>2006-05-04</re:DatumIzjave>
            <re:OrganVlasti>OrganVlasti2</re:OrganVlasti>
            <re:DatumPotrazivanjaInformacija>2006-05-04</re:DatumPotrazivanjaInformacija>
        </re:Paragraf1>
    </re:Obrazlozenje>
    <re:Poverenik>
        <re:Ime>Ime0</re:Ime>
        <re:Prezime>Prezime0</re:Prezime>
    </re:Poverenik>
</re:resenje>
